using Api.Dtos;
using AutoMapper;
using Domain.Entities;

namespace Api.Profiles;
public class MappignProfiles: Profile{
    public MappignProfiles(){
        
        CreateMap<ChargeDto,Charge>()
            .ReverseMap();
        CreateMap<AddressDto,Address>()
            .ReverseMap();
        CreateMap<CityDto,City>()
            .ReverseMap();
        CreateMap<ContactCategoryDto,ContactCategory>()
            .ReverseMap();
        CreateMap<ContactTypeDto,ContactType>()
            .ReverseMap();
        CreateMap<CountryDto,Country>()
            .ReverseMap();
        CreateMap<DepartmentDto,Department>()
            .ReverseMap();
        CreateMap<DocumentTypeDto,DocumentType>()
            .ReverseMap();
        CreateMap<EmployeeDto,Employee>()
            .ReverseMap();
        CreateMap<EpsTypeDto,EpsType>()
            .ReverseMap();
        CreateMap<InventoryDto,Inventory>()
            .ReverseMap();
        CreateMap<MedicineDto,Medicine>()
            .ReverseMap();
        CreateMap<MedicineBrandDto,MedicineBrand>()
            .ReverseMap();
        CreateMap<MedicineCategoryDto,MedicineCategory>()
            .ReverseMap();
        CreateMap<MedicineInfoDto,MedicineInfo>()
            .ReverseMap();
        CreateMap<MedicineInfoSimpleDto,MedicineInfo>()
            .ReverseMap();            
        CreateMap<MedicinePresentationDto,MedicinePresentation>()
            .ReverseMap();
        CreateMap<PersonDto,Person>()
            .ReverseMap();
        CreateMap<RecipeDto,Recipe>()
            .ReverseMap();
        CreateMap<RoleDto,Role>()
            .ReverseMap();
        CreateMap<SaleDto,Sale>()
            .ReverseMap();
        CreateMap<ShoppingDto,Shopping>()
            .ReverseMap();
        CreateMap<StateDto,State>()
            .ReverseMap();
        CreateMap<SupplierTypeDto,SupplierType>()
            .ReverseMap();
        CreateMap<PersonTypeDto,PersonType>()
            .ReverseMap();
        CreateMap<UserDto,User>()
            .ReverseMap();

        //-Dto with id
        CreateMap<ChargeWithIdDto,Charge>()
            .ReverseMap();
        CreateMap<AddressWithIdDto,Address>()
            .ReverseMap();
        CreateMap<CityWithIdDto,City>()
            .ReverseMap();
        CreateMap<ContactCategoryWithIdDto,ContactCategory>()
            .ReverseMap();
        CreateMap<ContactTypeWithIdDto,ContactType>()
            .ReverseMap();
        CreateMap<CountryWithIdDto,Country>()
            .ReverseMap();
        CreateMap<DepartmentWithIdDto,Department>()
            .ReverseMap();
        CreateMap<DocumentTypeWithIdDto,DocumentType>()
            .ReverseMap();
        CreateMap<EmployeeWithIdDto,Employee>()
            .ReverseMap();
        CreateMap<EpsTypeWithIdDto,EpsType>()
            .ReverseMap();
        CreateMap<InventoryWithIdDto,Inventory>()
            .ReverseMap();
        CreateMap<MedicineWithIdDto,Medicine>()
            .ReverseMap();
        CreateMap<MedicineBrandWithIdDto,MedicineBrand>()
            .ReverseMap();
        CreateMap<MedicineCategoryWithIdDto,MedicineCategory>()
            .ReverseMap();
        CreateMap<MedicineInfoWithIdDto,MedicineInfo>()
            .ReverseMap();
        CreateMap<MedicinePresentationWithIdDto,MedicinePresentation>()
            .ReverseMap();
        CreateMap<PersonWithIdDto,Person>()
            .ReverseMap();
        CreateMap<RecipeWithIdDto,Recipe>()
            .ReverseMap();
        CreateMap<RoleWithIdDto,Role>()
            .ReverseMap();
        CreateMap<SaleWithIdDto,Sale>()
            .ReverseMap();
        CreateMap<ShoppingWithIdDto,Shopping>()
            .ReverseMap();
        CreateMap<StateWithIdDto,State>()
            .ReverseMap();
        CreateMap<SupplierTypeWithIdDto,SupplierType>()
            .ReverseMap();
        CreateMap<PersonTypeWithIdDto,PersonType>()
            .ReverseMap();
        CreateMap<UserWithIdDto,User>()
            .ReverseMap();
    }
}